css3 = [
    {'color': 'aliceblue',
        'hex': '#f0f8ff',
        'rgb': (240, 248, 255)},
    {'color': 'antiquewhite',
        'hex': '#faebd7',
        'rgb': (250, 235, 215)},
    {'color': 'aqua',
        'hex': '#00ffff',
        'rgb': (0, 255, 255)},
    {'color': 'aquamarine',
        'hex': '#7fffd4',
        'rgb': (127, 255, 212)},
    {'color': 'azure',
        'hex': '#f0ffff',
        'rgb': (240, 255, 255)},
    {'color': 'beige',
        'hex': '#f5f5dc',
        'rgb': (245, 245, 220)},
    {'color': 'bisque',
        'hex': '#ffe4c4',
        'rgb': (255, 228, 196)},
    {'color': 'black',
        'hex': '#000000',
        'rgb': (0, 0, 0)},
    {'color': 'blanchedalmond',
        'hex': '#ffebcd',
        'rgb': (255, 235, 205)},
    {'color': 'blue',
        'hex': '#0000ff',
        'rgb': (0, 0, 255)},
    {'color': 'blueviolet',
        'hex': '#8a2be2',
        'rgb': (138, 43, 226)},
    {'color': 'brown',
        'hex': '#a52a2a',
        'rgb': (165, 42, 42)},
    {'color': 'burlywood',
        'hex': '#deb887',
        'rgb': (222, 184, 135)},
    {'color': 'cadetblue',
        'hex': '#5f9ea0',
        'rgb': (95, 158, 160)},
    {'color': 'chartreuse',
        'hex': '#7fff00',
        'rgb': (127, 255, 0)},
    {'color': 'chocolate',
        'hex': '#d2691e',
        'rgb': (210, 105, 30)},
    {'color': 'coral',
        'hex': '#ff7f50',
        'rgb': (255, 127, 80)},
    {'color': 'cornflowerblue',
        'hex': '#6495ed',
        'rgb': (100, 149, 237)},
    {'color': 'cornsilk',
        'hex': '#fff8dc',
        'rgb': (255, 248, 220)},
    {'color': 'crimson',
        'hex': '#dc143c',
        'rgb': (220, 20, 60)},
    {'color': 'cyan',
        'hex': '#00ffff',
        'rgb': (0, 255, 255)},
    {'color': 'darkblue',
        'hex': '#00008b',
        'rgb': (0, 0, 139)},
    {'color': 'darkcyan',
        'hex': '#008b8b',
        'rgb': (0, 139, 139)},
    {'color': 'darkgoldenrod',
        'hex': '#b8860b',
        'rgb': (184, 134, 11)},
    {'color': 'darkgray',
        'hex': '#a9a9a9',
        'rgb': (169, 169, 169)},
    {'color': 'darkgreen',
        'hex': '#006400',
        'rgb': (0, 100, 0)},
    {'color': 'darkgrey',
        'hex': '#a9a9a9',
        'rgb': (169, 169, 169)},
    {'color': 'darkkhaki',
        'hex': '#bdb76b',
        'rgb': (189, 183, 107)},
    {'color': 'darkmagenta',
        'hex': '#8b008b',
        'rgb': (139, 0, 139)},
    {'color': 'darkolivegreen',
        'hex': '#556b2f',
        'rgb': (85, 107, 47)},
    {'color': 'darkorange',
        'hex': '#ff8c00',
        'rgb': (255, 140, 0)},
    {'color': 'darkorchid',
        'hex': '#9932cc',
        'rgb': (153, 50, 204)},
    {'color': 'darkred',
        'hex': '#8b0000',
        'rgb': (139, 0, 0)},
    {'color': 'darksalmon',
        'hex': '#e9967a',
        'rgb': (233, 150, 122)},
    {'color': 'darkseagreen',
        'hex': '#8fbc8f',
        'rgb': (143, 188, 143)},
    {'color': 'darkslateblue',
        'hex': '#483d8b',
        'rgb': (72, 61, 139)},
    {'color': 'darkslategray',
        'hex': '#2f4f4f',
        'rgb': (47, 79, 79)},
    {'color': 'darkslategrey',
        'hex': '#2f4f4f',
        'rgb': (47, 79, 79)},
    {'color': 'darkturquoise',
        'hex': '#00ced1',
        'rgb': (0, 206, 209)},
    {'color': 'darkviolet',
        'hex': '#9400d3',
        'rgb': (148, 0, 211)},
    {'color': 'deeppink',
        'hex': '#ff1493',
        'rgb': (255, 20, 147)},
    {'color': 'deepskyblue',
        'hex': '#00bfff',
        'rgb': (0, 191, 255)},
    {'color': 'dimgray',
        'hex': '#696969',
        'rgb': (105, 105, 105)},
    {'color': 'dimgrey',
        'hex': '#696969',
        'rgb': (105, 105, 105)},
    {'color': 'dodgerblue',
        'hex': '#1e90ff',
        'rgb': (30, 144, 255)},
    {'color': 'firebrick',
        'hex': '#b22222',
        'rgb': (178, 34, 34)},
    {'color': 'floralwhite',
        'hex': '#fffaf0',
        'rgb': (255, 250, 240)},
    {'color': 'forestgreen',
        'hex': '#228b22',
        'rgb': (34, 139, 34)},
    {'color': 'fuchsia',
        'hex': '#ff00ff',
        'rgb': (255, 0, 255)},
    {'color': 'gainsboro',
        'hex': '#dcdcdc',
        'rgb': (220, 220, 220)},
    {'color': 'ghostwhite',
        'hex': '#f8f8ff',
        'rgb': (248, 248, 255)},
    {'color': 'gold',
        'hex': '#ffd700',
        'rgb': (255, 215, 0)},
    {'color': 'goldenrod',
        'hex': '#daa520',
        'rgb': (218, 165, 32)},
    {'color': 'gray',
        'hex': '#808080',
        'rgb': (128, 128, 128)},
    {'color': 'green',
        'hex': '#008000',
        'rgb': (0, 128, 0)},
    {'color': 'greenyellow',
        'hex': '#adff2f',
        'rgb': (173, 255, 47)},
    {'color': 'grey',
        'hex': '#808080',
        'rgb': (128, 128, 128)},
    {'color': 'honeydew',
        'hex': '#f0fff0',
        'rgb': (240, 255, 240)},
    {'color': 'hotpink',
        'hex': '#ff69b4',
        'rgb': (255, 105, 180)},
    {'color': 'indianred',
        'hex': '#cd5c5c',
        'rgb': (205, 92, 92)},
    {'color': 'indigo',
        'hex': '#4b0082',
        'rgb': (75, 0, 130)},
    {'color': 'ivory',
        'hex': '#fffff0',
        'rgb': (255, 255, 240)},
    {'color': 'khaki',
        'hex': '#f0e68c',
        'rgb': (240, 230, 140)},
    {'color': 'lavender',
        'hex': '#e6e6fa',
        'rgb': (230, 230, 250)},
    {'color': 'lavenderblush',
        'hex': '#fff0f5',
        'rgb': (255, 240, 245)},
    {'color': 'lawngreen',
        'hex': '#7cfc00',
        'rgb': (124, 252, 0)},
    {'color': 'lemonchiffon',
        'hex': '#fffacd',
        'rgb': (255, 250, 205)},
    {'color': 'lightblue',
        'hex': '#add8e6',
        'rgb': (173, 216, 230)},
    {'color': 'lightcoral',
        'hex': '#f08080',
        'rgb': (240, 128, 128)},
    {'color': 'lightcyan',
        'hex': '#e0ffff',
        'rgb': (224, 255, 255)},
    {'color': 'lightgoldenrodyellow',
        'hex': '#fafad2',
        'rgb': (250, 250, 210)},
    {'color': 'lightgray',
        'hex': '#d3d3d3',
        'rgb': (211, 211, 211)},
    {'color': 'lightgreen',
        'hex': '#90ee90',
        'rgb': (144, 238, 144)},
    {'color': 'lightgrey',
        'hex': '#d3d3d3',
        'rgb': (211, 211, 211)},
    {'color': 'lightpink',
        'hex': '#ffb6c1',
        'rgb': (255, 182, 193)},
    {'color': 'lightsalmon',
        'hex': '#ffa07a',
        'rgb': (255, 160, 122)},
    {'color': 'lightseagreen',
        'hex': '#20b2aa',
        'rgb': (32, 178, 170)},
    {'color': 'lightskyblue',
        'hex': '#87cefa',
        'rgb': (135, 206, 250)},
    {'color': 'lightslategray',
        'hex': '#778899',
        'rgb': (119, 136, 153)},
    {'color': 'lightslategrey',
        'hex': '#778899',
        'rgb': (119, 136, 153)},
    {'color': 'lightsteelblue',
        'hex': '#b0c4de',
        'rgb': (176, 196, 222)},
    {'color': 'lightyellow',
        'hex': '#ffffe0',
        'rgb': (255, 255, 224)},
    {'color': 'lime',
        'hex': '#00ff00',
        'rgb': (0, 255, 0)},
    {'color': 'limegreen',
        'hex': '#32cd32',
        'rgb': (50, 205, 50)},
    {'color': 'linen',
        'hex': '#faf0e6',
        'rgb': (250, 240, 230)},
    {'color': 'magenta',
        'hex': '#ff00ff',
        'rgb': (255, 0, 255)},
    {'color': 'maroon',
        'hex': '#800000',
        'rgb': (128, 0, 0)},
    {'color': 'mediumaquamarine',
        'hex': '#66cdaa',
        'rgb': (102, 205, 170)},
    {'color': 'mediumblue',
        'hex': '#0000cd',
        'rgb': (0, 0, 205)},
    {'color': 'mediumorchid',
        'hex': '#ba55d3',
        'rgb': (186, 85, 211)},
    {'color': 'mediumpurple',
        'hex': '#9370db',
        'rgb': (147, 112, 219)},
    {'color': 'mediumseagreen',
        'hex': '#3cb371',
        'rgb': (60, 179, 113)},
    {'color': 'mediumslateblue',
        'hex': '#7b68ee',
        'rgb': (123, 104, 238)},
    {'color': 'mediumspringgreen',
        'hex': '#00fa9a',
        'rgb': (0, 250, 154)},
    {'color': 'mediumturquoise',
        'hex': '#48d1cc',
        'rgb': (72, 209, 204)},
    {'color': 'mediumvioletred',
        'hex': '#c71585',
        'rgb': (199, 21, 133)},
    {'color': 'midnightblue',
        'hex': '#191970',
        'rgb': (25, 25, 112)},
    {'color': 'mintcream',
        'hex': '#f5fffa',
        'rgb': (245, 255, 250)},
    {'color': 'mistyrose',
        'hex': '#ffe4e1',
        'rgb': (255, 228, 225)},
    {'color': 'moccasin',
        'hex': '#ffe4b5',
        'rgb': (255, 228, 181)},
    {'color': 'navajowhite',
        'hex': '#ffdead',
        'rgb': (255, 222, 173)},
    {'color': 'navy',
        'hex': '#000080',
        'rgb': (0, 0, 128)},
    {'color': 'oldlace',
        'hex': '#fdf5e6',
        'rgb': (253, 245, 230)},
    {'color': 'olive',
        'hex': '#808000',
        'rgb': (128, 128, 0)},
    {'color': 'olivedrab',
        'hex': '#6b8e23',
        'rgb': (107, 142, 35)},
    {'color': 'orange',
        'hex': '#ffa500',
        'rgb': (255, 165, 0)},
    {'color': 'orangered',
        'hex': '#ff4500',
        'rgb': (255, 69, 0)},
    {'color': 'orchid',
        'hex': '#da70d6',
        'rgb': (218, 112, 214)},
    {'color': 'palegoldenrod',
        'hex': '#eee8aa',
        'rgb': (238, 232, 170)},
    {'color': 'palegreen',
        'hex': '#98fb98',
        'rgb': (152, 251, 152)},
    {'color': 'paleturquoise',
        'hex': '#afeeee',
        'rgb': (175, 238, 238)},
    {'color': 'palevioletred',
        'hex': '#db7093',
        'rgb': (219, 112, 147)},
    {'color': 'papayawhip',
        'hex': '#ffefd5',
        'rgb': (255, 239, 213)},
    {'color': 'peachpuff',
        'hex': '#ffdab9',
        'rgb': (255, 218, 185)},
    {'color': 'peru',
        'hex': '#cd853f',
        'rgb': (205, 133, 63)},
    {'color': 'pink',
        'hex': '#ffc0cb',
        'rgb': (255, 192, 203)},
    {'color': 'plum',
        'hex': '#dda0dd',
        'rgb': (221, 160, 221)},
    {'color': 'powderblue',
        'hex': '#b0e0e6',
        'rgb': (176, 224, 230)},
    {'color': 'purple',
        'hex': '#800080',
        'rgb': (128, 0, 128)},
    {'color': 'red',
        'hex': '#ff0000',
        'rgb': (255, 0, 0)},
    {'color': 'rosybrown',
        'hex': '#bc8f8f',
        'rgb': (188, 143, 143)},
    {'color': 'royalblue',
        'hex': '#4169e1',
        'rgb': (65, 105, 225)},
    {'color': 'saddlebrown',
        'hex': '#8b4513',
        'rgb': (139, 69, 19)},
    {'color': 'salmon',
        'hex': '#fa8072',
        'rgb': (250, 128, 114)},
    {'color': 'sandybrown',
        'hex': '#f4a460',
        'rgb': (244, 164, 96)},
    {'color': 'seagreen',
        'hex': '#2e8b57',
        'rgb': (46, 139, 87)},
    {'color': 'seashell',
        'hex': '#fff5ee',
        'rgb': (255, 245, 238)},
    {'color': 'sienna',
        'hex': '#a0522d',
        'rgb': (160, 82, 45)},
    {'color': 'silver',
        'hex': '#c0c0c0',
        'rgb': (192, 192, 192)},
    {'color': 'skyblue',
        'hex': '#87ceeb',
        'rgb': (135, 206, 235)},
    {'color': 'slateblue',
        'hex': '#6a5acd',
        'rgb': (106, 90, 205)},
    {'color': 'slategray',
        'hex': '#708090',
        'rgb': (112, 128, 144)},
    {'color': 'slategrey',
        'hex': '#708090',
        'rgb': (112, 128, 144)},
    {'color': 'snow',
        'hex': '#fffafa',
        'rgb': (255, 250, 250)},
    {'color': 'springgreen',
        'hex': '#00ff7f',
        'rgb': (0, 255, 127)},
    {'color': 'steelblue',
        'hex': '#4682b4',
        'rgb': (70, 130, 180)},
    {'color': 'tan',
        'hex': '#d2b48c',
        'rgb': (210, 180, 140)},
    {'color': 'teal',
        'hex': '#008080',
        'rgb': (0, 128, 128)},
    {'color': 'thistle',
        'hex': '#d8bfd8',
        'rgb': (216, 191, 216)},
    {'color': 'tomato',
        'hex': '#ff6347',
        'rgb': (255, 99, 71)},
    {'color': 'turquoise',
        'hex': '#40e0d0',
        'rgb': (64, 224, 208)},
    {'color': 'violet',
        'hex': '#ee82ee',
        'rgb': (238, 130, 238)},
    {'color': 'wheat',
        'hex': '#f5deb3',
        'rgb': (245, 222, 179)},
    {'color': 'white',
        'hex': '#ffffff',
        'rgb': (255, 255, 255)},
    {'color': 'whitesmoke',
        'hex': '#f5f5f5',
        'rgb': (245, 245, 245)},
    {'color': 'yellow',
        'hex': '#ffff00',
        'rgb': (255, 255, 0)},
    {'color': 'yellowgreen',
        'hex': '#9acd32',
        'rgb': (154, 205, 50)},
]

material_design = [
    # Red
    {'color': 'red-50',
        'hex': '#ffebee',
        'rgb': (255, 235, 238)},
    {'color': 'red-100',
        'hex': '#ffcdd2',
        'rgb': (255, 205, 210)},
    {'color': 'red-200',
        'hex': '#ef9a9a',
        'rgb': (239, 154, 154)},
    {'color': 'red-300',
        'hex': '#e57373',
        'rgb': (229, 115, 115)},
    {'color': 'red-400',
        'hex': '#ef5350',
        'rgb': (239, 83, 80)},
    {'color': 'red-500',
        'hex': '#f44336',
        'rgb': (244, 67, 54)},
    {'color': 'red-600',
        'hex': '#e53935',
        'rgb': (229, 57, 53)},
    {'color': 'red-700',
        'hex': '#d32f2f',
        'rgb': (211, 47, 47)},
    {'color': 'red-800',
        'hex': '#c62828',
        'rgb': (198, 40, 40)},
    {'color': 'red-900',
        'hex': '#b71c1c',
        'rgb': (183, 28, 28)},
    {'color': 'red-a100',
        'hex': '#ff8a80',
        'rgb': (255, 138, 128)},
    {'color': 'red-a200',
        'hex': '#ff5252',
        'rgb': (255, 82, 82)},
    {'color': 'red-a400',
        'hex': '#ff1744',
        'rgb': (255, 23, 68)},
    {'color': 'red-a700',
        'hex': '#d50000',
        'rgb': (213, 0, 0)},
    # Pink
    {'color': 'pink-50',
        'hex': '',
        'rgb': null},
    {'color': 'pink-100',
        'hex': '',
        'rgb': null},
    {'color': 'pink-200',
        'hex': '',
        'rgb': null},
    {'color': 'pink-300',
        'hex': '',
        'rgb': null},
    {'color': 'pink-400',
        'hex': '',
        'rgb': null},
    {'color': 'pink-500',
        'hex': '',
        'rgb': null},
    {'color': 'pink-600',
        'hex': '',
        'rgb': null},
    {'color': 'pink-700',
        'hex': '',
        'rgb': null},
    {'color': 'pink-800',
        'hex': '',
        'rgb': null},
    {'color': 'pink-900',
        'hex': '',
        'rgb': null},
    {'color': 'pink-a100',
        'hex': '',
        'rgb': null},
    {'color': 'pink-a200',
        'hex': '',
        'rgb': null},
    {'color': 'pink-a400',
        'hex': '',
        'rgb': null},
    {'color': 'pink-a700',
        'hex': '',
        'rgb': null},
    # Purple
    {'color': 'purple-50',
        'hex': '',
        'rgb': null},
    {'color': 'purple-100',
        'hex': '',
        'rgb': null},
    {'color': 'purple-200',
        'hex': '',
        'rgb': null},
    {'color': 'purple-300',
        'hex': '',
        'rgb': null},
    {'color': 'purple-400',
        'hex': '',
        'rgb': null},
    {'color': 'purple-500',
        'hex': '',
        'rgb': null},
    {'color': 'purple-600',
        'hex': '',
        'rgb': null},
    {'color': 'purple-700',
        'hex': '',
        'rgb': null},
    {'color': 'purple-800',
        'hex': '',
        'rgb': null},
    {'color': 'purple-900',
        'hex': '',
        'rgb': null},
    {'color': 'purple-a100',
        'hex': '',
        'rgb': null},
    {'color': 'purple-a200',
        'hex': '',
        'rgb': null},
    {'color': 'purple-a400',
        'hex': '',
        'rgb': null},
    {'color': 'purple-a700',
        'hex': '',
        'rgb': null},
    # Deep Purple
    {'color': 'deeppurple-50',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-100',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-200',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-300',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-400',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-500',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-600',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-700',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-800',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-900',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-a100',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-a200',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-a400',
        'hex': '',
        'rgb': null},
    {'color': 'deeppurple-a700',
        'hex': '',
        'rgb': null},
    # Indigo
    {'color': 'indigo-50',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-100',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-200',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-300',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-400',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-500',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-600',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-700',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-800',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-900',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-a100',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-a200',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-a400',
        'hex': '',
        'rgb': null},
    {'color': 'indigo-a700',
        'hex': '',
        'rgb': null},
    # Blue
    {'color': 'blue-50',
        'hex': '',
        'rgb': null},
    {'color': 'blue-100',
        'hex': '',
        'rgb': null},
    {'color': 'blue-200',
        'hex': '',
        'rgb': null},
    {'color': 'blue-300',
        'hex': '',
        'rgb': null},
    {'color': 'blue-400',
        'hex': '',
        'rgb': null},
    {'color': 'blue-500',
        'hex': '',
        'rgb': null},
    {'color': 'blue-600',
        'hex': '',
        'rgb': null},
    {'color': 'blue-700',
        'hex': '',
        'rgb': null},
    {'color': 'blue-800',
        'hex': '',
        'rgb': null},
    {'color': 'blue-900',
        'hex': '',
        'rgb': null},
    {'color': 'blue-a100',
        'hex': '',
        'rgb': null},
    {'color': 'blue-a200',
        'hex': '',
        'rgb': null},
    {'color': 'blue-a400',
        'hex': '',
        'rgb': null},
    {'color': 'blue-a700',
        'hex': '',
        'rgb': null},
    # Light Blue
    {'color': 'lightblue-50',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-100',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-200',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-300',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-400',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-500',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-600',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-700',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-800',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-900',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-a100',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-a200',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-a400',
        'hex': '',
        'rgb': null},
    {'color': 'lightblue-a700',
        'hex': '',
        'rgb': null},
    # Cyan
    {'color': 'cyan-50',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-100',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-200',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-300',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-400',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-500',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-600',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-700',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-800',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-900',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-a100',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-a200',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-a400',
        'hex': '',
        'rgb': null},
    {'color': 'cyan-a700',
        'hex': '',
        'rgb': null},
    # Teal
    {'color': 'teal-50',
        'hex': '',
        'rgb': null},
    {'color': 'teal-100',
        'hex': '',
        'rgb': null},
    {'color': 'teal-200',
        'hex': '',
        'rgb': null},
    {'color': 'teal-300',
        'hex': '',
        'rgb': null},
    {'color': 'teal-400',
        'hex': '',
        'rgb': null},
    {'color': 'teal-500',
        'hex': '',
        'rgb': null},
    {'color': 'teal-600',
        'hex': '',
        'rgb': null},
    {'color': 'teal-700',
        'hex': '',
        'rgb': null},
    {'color': 'teal-800',
        'hex': '',
        'rgb': null},
    {'color': 'teal-900',
        'hex': '',
        'rgb': null},
    {'color': 'teal-a100',
        'hex': '',
        'rgb': null},
    {'color': 'teal-a200',
        'hex': '',
        'rgb': null},
    {'color': 'teal-a400',
        'hex': '',
        'rgb': null},
    {'color': 'teal-a700',
        'hex': '',
        'rgb': null},
    # Green
    {'color': 'green-50',
        'hex': '',
        'rgb': null},
    {'color': 'green-100',
        'hex': '',
        'rgb': null},
    {'color': 'green-200',
        'hex': '',
        'rgb': null},
    {'color': 'green-300',
        'hex': '',
        'rgb': null},
    {'color': 'green-400',
        'hex': '',
        'rgb': null},
    {'color': 'green-500',
        'hex': '',
        'rgb': null},
    {'color': 'green-600',
        'hex': '',
        'rgb': null},
    {'color': 'green-700',
        'hex': '',
        'rgb': null},
    {'color': 'green-800',
        'hex': '',
        'rgb': null},
    {'color': 'green-900',
        'hex': '',
        'rgb': null},
    {'color': 'green-a100',
        'hex': '',
        'rgb': null},
    {'color': 'green-a200',
        'hex': '',
        'rgb': null},
    {'color': 'green-a400',
        'hex': '',
        'rgb': null},
    {'color': 'green-a700',
        'hex': '',
        'rgb': null},
    # Light Green
    {'color': 'lightgreen-50',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-100',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-200',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-300',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-400',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-500',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-600',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-700',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-800',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-900',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-a100',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-a200',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-a400',
        'hex': '',
        'rgb': null},
    {'color': 'lightgreen-a700',
        'hex': '',
        'rgb': null},
    # Lime
    {'color': 'lime-50',
        'hex': '',
        'rgb': null},
    {'color': 'lime-100',
        'hex': '',
        'rgb': null},
    {'color': 'lime-200',
        'hex': '',
        'rgb': null},
    {'color': 'lime-300',
        'hex': '',
        'rgb': null},
    {'color': 'lime-400',
        'hex': '',
        'rgb': null},
    {'color': 'lime-500',
        'hex': '',
        'rgb': null},
    {'color': 'lime-600',
        'hex': '',
        'rgb': null},
    {'color': 'lime-700',
        'hex': '',
        'rgb': null},
    {'color': 'lime-800',
        'hex': '',
        'rgb': null},
    {'color': 'lime-900',
        'hex': '',
        'rgb': null},
    {'color': 'lime-a100',
        'hex': '',
        'rgb': null},
    {'color': 'lime-a200',
        'hex': '',
        'rgb': null},
    {'color': 'lime-a400',
        'hex': '',
        'rgb': null},
    {'color': 'lime-a700',
        'hex': '',
        'rgb': null},
    # Yellow
    {'color': 'yellow-50',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-100',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-200',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-300',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-400',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-500',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-600',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-700',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-800',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-900',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-a100',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-a200',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-a400',
        'hex': '',
        'rgb': null},
    {'color': 'yellow-a700',
        'hex': '',
        'rgb': null},
    # Amber
    {'color': 'amber-50',
        'hex': '',
        'rgb': null},
    {'color': 'amber-100',
        'hex': '',
        'rgb': null},
    {'color': 'amber-200',
        'hex': '',
        'rgb': null},
    {'color': 'amber-300',
        'hex': '',
        'rgb': null},
    {'color': 'amber-400',
        'hex': '',
        'rgb': null},
    {'color': 'amber-500',
        'hex': '',
        'rgb': null},
    {'color': 'amber-600',
        'hex': '',
        'rgb': null},
    {'color': 'amber-700',
        'hex': '',
        'rgb': null},
    {'color': 'amber-800',
        'hex': '',
        'rgb': null},
    {'color': 'amber-900',
        'hex': '',
        'rgb': null},
    {'color': 'amber-a100',
        'hex': '',
        'rgb': null},
    {'color': 'amber-a200',
        'hex': '',
        'rgb': null},
    {'color': 'amber-a400',
        'hex': '',
        'rgb': null},
    {'color': 'amber-a700',
        'hex': '',
        'rgb': null},
    # Orange
    {'color': 'orange-50',
        'hex': '',
        'rgb': null},
    {'color': 'orange-100',
        'hex': '',
        'rgb': null},
    {'color': 'orange-200',
        'hex': '',
        'rgb': null},
    {'color': 'orange-300',
        'hex': '',
        'rgb': null},
    {'color': 'orange-400',
        'hex': '',
        'rgb': null},
    {'color': 'orange-500',
        'hex': '',
        'rgb': null},
    {'color': 'orange-600',
        'hex': '',
        'rgb': null},
    {'color': 'orange-700',
        'hex': '',
        'rgb': null},
    {'color': 'orange-800',
        'hex': '',
        'rgb': null},
    {'color': 'orange-900',
        'hex': '',
        'rgb': null},
    {'color': 'orange-a100',
        'hex': '',
        'rgb': null},
    {'color': 'orange-a200',
        'hex': '',
        'rgb': null},
    {'color': 'orange-a400',
        'hex': '',
        'rgb': null},
    {'color': 'orange-a700',
        'hex': '',
        'rgb': null},
    # Deep Orange
    {'color': 'deeporange-50',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-100',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-200',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-300',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-400',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-500',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-600',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-700',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-800',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-900',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-a100',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-a200',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-a400',
        'hex': '',
        'rgb': null},
    {'color': 'deeporange-a700',
        'hex': '',
        'rgb': null},
    # Brown
    {'color': 'brown-50',
        'hex': '',
        'rgb': null},
    {'color': 'brown-100',
        'hex': '',
        'rgb': null},
    {'color': 'brown-200',
        'hex': '',
        'rgb': null},
    {'color': 'brown-300',
        'hex': '',
        'rgb': null},
    {'color': 'brown-400',
        'hex': '',
        'rgb': null},
    {'color': 'brown-500',
        'hex': '',
        'rgb': null},
    {'color': 'brown-600',
        'hex': '',
        'rgb': null},
    {'color': 'brown-700',
        'hex': '',
        'rgb': null},
    {'color': 'brown-800',
        'hex': '',
        'rgb': null},
    {'color': 'brown-900',
        'hex': '',
        'rgb': null},
    # Grey
    {'color': 'grey-50',
        'hex': '',
        'rgb': null},
    {'color': 'grey-100',
        'hex': '',
        'rgb': null},
    {'color': 'grey-200',
        'hex': '',
        'rgb': null},
    {'color': 'grey-300',
        'hex': '',
        'rgb': null},
    {'color': 'grey-400',
        'hex': '',
        'rgb': null},
    {'color': 'grey-500',
        'hex': '',
        'rgb': null},
    {'color': 'grey-600',
        'hex': '',
        'rgb': null},
    {'color': 'grey-700',
        'hex': '',
        'rgb': null},
    {'color': 'grey-800',
        'hex': '',
        'rgb': null},
    {'color': 'grey-900',
        'hex': '',
        'rgb': null},
    # Blue Grey
    {'color': 'bluegrey-50',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-100',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-200',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-300',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-400',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-500',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-600',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-700',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-800',
        'hex': '',
        'rgb': null},
    {'color': 'bluegrey-900',
        'hex': '',
        'rgb': null},
    # Black
    {'color': 'black',
        'hex': '',
        'rgb': null},
    # White
    {'color': 'white',
        'hex': '',
        'rgb': null},
]
